use std::path::Path;
use anyhow::{Context, Result};
use console::style;

use crate::config::schema::ProjectConfig;
use crate::core::stack::Stack;

pub struct ProjectGenerator {
    config: ProjectConfig,
}

impl ProjectGenerator {
    pub fn new(config: ProjectConfig) -> Self {
        Self { config }
    }

    pub fn generate(&self, path: &Path, _stack: &Stack) -> Result<()> {
        // Create project directory
        std::fs::create_dir_all(path)
            .context("Failed to create project directory")?;

        // Create src directory
        std::fs::create_dir_all(path.join("src"))
            .context("Failed to create src directory")?;

        // Generate files
        self.generate_cargo_toml(path, _stack)?;
        self.generate_main_rs(path, _stack)?;
        self.generate_config_rs(path)?;
        self.generate_state_rs(path)?;
        self.generate_error_rs(path)?;
        self.generate_env_example(path)?;
        self.generate_gitignore(path)?;
        self.generate_nexus_toml(path)?;

        // Generate database files if enabled
        if self.config.database != "None" {
            self.generate_database_rs(path)?;
            self.generate_migrations_dir(path)?;
        }

        // Create directory structure
        self.create_directories(path)?;

        println!("  {} Project structure", style("✓").green());
        println!("  {} Cargo.toml", style("✓").green());
        println!("  {} Configuration", style("✓").green());
        println!("  {} Routes", style("✓").green());
        println!("  {} Error handling", style("✓").green());
        println!("  {} Logging", style("✓").green());

        Ok(())
    }

    fn generate_cargo_toml(&self, path: &Path, stack: &Stack) -> Result<()> {
        let dependencies = stack.dependencies();
        let deps_str: Vec<String> = dependencies.iter().map(|d| {
            if d.features.is_empty() {
                format!("{} = \"{}\"", d.name, d.version)
            } else {
                let features = d.features.iter()
                    .map(|f| format!("\"{}\"", f))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{} = {{ version = \"{}\", features = [{}] }}", d.name, d.version, features)
            }
        }).collect();

        let cargo_toml = format!(
            r#"[package]
name = "{}"
version = "0.1.0"
edition = "2021"
description = "A backend project generated by Oxide"
license = "MIT"

[dependencies]
{}

[tool.nexus]
version = "{}""#,
            self.config.name,
            deps_str.join("\n"),
            env!("CARGO_PKG_VERSION")
        );

        std::fs::write(path.join("Cargo.toml"), cargo_toml)
            .context("Failed to write Cargo.toml")?;

        Ok(())
    }

    fn generate_main_rs(&self, path: &Path, _stack: &Stack) -> Result<()> {
        // Convert hyphens to underscores for Rust crate name
        let _crate_name = self.config.name.replace('-', "_");
        let db_module = if self.config.database != "None" {
            "mod database;\n"
        } else {
            ""
        };

        let main_rs = format!(
            r#"use anyhow::Result;
use std::net::SocketAddr;
use tracing_subscriber::{{layer::SubscriberExt, util::SubscriberInitExt}};

mod config;
mod error;
mod handlers;
mod middleware;
mod models;
mod repositories;
mod routes;
mod services;
mod state;
{db_module}
#[tokio::main]
async fn main() -> Result<()> {{
    // Initialize tracing
    tracing_subscriber::registry()
        .with(
            tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| "info".into()),
        )
        .with(tracing_subscriber::fmt::layer())
        .init();

    // Load environment variables
    dotenvy::dotenv().ok();

    // Build application state
    let state = state::AppState::new().await?;

    // Build router
    let app = routes::router(state);

    // Run server
    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    tracing::info!("Server listening on {{}}", addr);

    let listener = tokio::net::TcpListener::bind(addr).await?;
    axum::serve(listener, app).await?;

    Ok(())
}}
"#
        );

        std::fs::write(path.join("src/main.rs"), main_rs)
            .context("Failed to write main.rs")?;

        Ok(())
    }

    fn generate_config_rs(&self, path: &Path) -> Result<()> {
        let config_rs = r#"use anyhow::{Context, Result};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct Config {
    pub server: ServerConfig,
}

#[derive(Debug, Deserialize)]
pub struct ServerConfig {
    #[serde(default = "default_host")]
    pub host: String,
    #[serde(default = "default_port")]
    pub port: u16,
}

fn default_host() -> String {
    "127.0.0.1".to_string()
}

fn default_port() -> u16 {
    3000
}

impl Config {
    pub fn from_env() -> Result<Self> {
        let config = config::Config::builder()
            .add_source(config::File::with_name("config"))
            .add_source(config::Environment::with_prefix("APP"))
            .build()
            .context("Failed to load configuration")?;

        config
            .try_deserialize()
            .context("Failed to deserialize configuration")
    }
}
"#;

        std::fs::write(path.join("src/config.rs"), config_rs)
            .context("Failed to write config.rs")?;

        Ok(())
    }

    fn generate_state_rs(&self, path: &Path) -> Result<()> {
        let state_rs = match self.config.database.as_str() {
            "PostgreSQL" => {
                r#"use anyhow::Result;
use sqlx::postgres::PgPool;

#[derive(Clone)]
pub struct AppState {
    pub db: PgPool,
}

impl AppState {
    pub async fn new() -> Result<Self> {
        let database_url = std::env::var("DATABASE_URL")
            .expect("DATABASE_URL must be set");

        let db = crate::database::create_pool(&database_url).await?;

        Ok(Self { db })
    }
}
"#
            }
            "MySQL" => {
                r#"use anyhow::Result;
use sqlx::mysql::MySqlPool;

#[derive(Clone)]
pub struct AppState {
    pub db: MySqlPool,
}

impl AppState {
    pub async fn new() -> Result<Self> {
        let database_url = std::env::var("DATABASE_URL")
            .expect("DATABASE_URL must be set");

        let db = crate::database::create_pool(&database_url).await?;

        Ok(Self { db })
    }
}
"#
            }
            "SQLite" => {
                r#"use anyhow::Result;
use sqlx::sqlite::SqlitePool;

#[derive(Clone)]
pub struct AppState {
    pub db: SqlitePool,
}

impl AppState {
    pub async fn new() -> Result<Self> {
        let database_url = std::env::var("DATABASE_URL")
            .unwrap_or_else(|_| "sqlite::memory:".to_string());

        let db = crate::database::create_pool(&database_url).await?;

        Ok(Self { db })
    }
}
"#
            }
            _ => {
                r#"use anyhow::Result;

#[derive(Clone)]
pub struct AppState {
    // Add your application state here
}

impl AppState {
    pub async fn new() -> Result<Self> {
        // Initialize your application state here
        Ok(Self {})
    }
}
"#
            }
        };

        std::fs::write(path.join("src/state.rs"), state_rs)
            .context("Failed to write state.rs")?;

        Ok(())
    }

    fn generate_error_rs(&self, path: &Path) -> Result<()> {
        let error_rs = r#"use axum::{
    http::StatusCode,
    response::{IntoResponse, Response},
    Json,
};
use serde_json::json;

#[derive(Debug)]
pub enum AppError {
    NotFound,
    InternalServerError(String),
    BadRequest(String),
}

impl IntoResponse for AppError {
    fn into_response(self) -> Response {
        let (status, message) = match self {
            AppError::NotFound => (StatusCode::NOT_FOUND, "Resource not found".to_string()),
            AppError::InternalServerError(msg) => (StatusCode::INTERNAL_SERVER_ERROR, msg),
            AppError::BadRequest(msg) => (StatusCode::BAD_REQUEST, msg),
        };

        let body = Json(json!({
            "error": {
                "message": message,
                "code": status.as_u16(),
            }
        }));

        (status, body).into_response()
    }
}

impl std::fmt::Display for AppError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AppError::NotFound => write!(f, "Not found"),
            AppError::InternalServerError(msg) => write!(f, "Internal server error: {}", msg),
            AppError::BadRequest(msg) => write!(f, "Bad request: {}", msg),
        }
    }
}

impl std::error::Error for AppError {}
"#;

        std::fs::write(path.join("src/error.rs"), error_rs)
            .context("Failed to write error.rs")?;

        Ok(())
    }

    fn generate_env_example(&self, path: &Path) -> Result<()> {
        let mut env_content = String::from(
            r#"# Server configuration
APP_SERVER_HOST=127.0.0.1
APP_SERVER_PORT=3000

# Logging
RUST_LOG=info
"#
        );

        if self.config.database != "None" {
            let db_url = match self.config.database.as_str() {
                "PostgreSQL" => format!(
                    "postgres://user:password@localhost:5432/{}",
                    self.config.name.replace('-', "_")
                ),
                "MySQL" => format!(
                    "mysql://user:password@localhost:3306/{}",
                    self.config.name.replace('-', "_")
                ),
                "SQLite" => "sqlite::memory:".to_string(),
                _ => String::new(),
            };
            env_content.push_str(&format!(
                r#"
# Database
DATABASE_URL={}
"#,
                db_url
            ));
        }

        if self.config.cache == "Redis" {
            env_content.push_str(
                r#"
# Redis
REDIS_URL=redis://localhost:6379
"#
            );
        }

        if self.config.auth == "JWT" {
            env_content.push_str(
                r#"
# JWT
JWT_SECRET=your-secret-key-here
JWT_EXPIRATION=3600
"#
            );
        }

        std::fs::write(path.join(".env.example"), &env_content)
            .context("Failed to write .env.example")?;

        // Create .env from .env.example
        std::fs::write(path.join(".env"), &env_content)
            .context("Failed to write .env")?;

        Ok(())
    }

    fn generate_gitignore(&self, path: &Path) -> Result<()> {
        let gitignore = r#"# Generated by Oxide
/target
.env
*.swp
*.swo
*~
.DS_Store
"#;

        std::fs::write(path.join(".gitignore"), gitignore)
            .context("Failed to write .gitignore")?;

        Ok(())
    }

    fn generate_nexus_toml(&self, path: &Path) -> Result<()> {
        let nexus_toml = format!(
            r#"[project]
name = "{}"
version = "0.1.0"
framework = "{}"
edition = "2021"

[database]
provider = "{}"

[auth]
provider = "{}"

[cache]
provider = "{}"

[tool.oxide]
version = "{}""#,
            self.config.name,
            self.config.framework.to_lowercase(),
            self.config.database.to_lowercase(),
            self.config.auth.to_lowercase(),
            self.config.cache.to_lowercase(),
            env!("CARGO_PKG_VERSION")
        );

        std::fs::write(path.join("nexus.toml"), nexus_toml)
            .context("Failed to write nexus.toml")?;

        Ok(())
    }

    fn generate_database_rs(&self, path: &Path) -> Result<()> {
        let db_rs = match self.config.database.as_str() {
            "PostgreSQL" => {
                r#"use sqlx::postgres::PgPool;
use anyhow::{Context, Result};

pub async fn create_pool(database_url: &str) -> Result<PgPool> {
    let pool = sqlx::postgres::PgPool::connect(database_url)
        .await
        .context("Failed to connect to PostgreSQL")?;

    // Run migrations
    sqlx::migrate!("./migrations")
        .run(&pool)
        .await
        .context("Failed to run migrations")?;

    Ok(pool)
}
"#
            }
            "MySQL" => {
                r#"use sqlx::mysql::MySqlPool;
use anyhow::{Context, Result};

pub async fn create_pool(database_url: &str) -> Result<MySqlPool> {
    let pool = sqlx::mysql::MySqlPool::connect(database_url)
        .await
        .context("Failed to connect to MySQL")?;

    // Run migrations
    sqlx::migrate!("./migrations")
        .run(&pool)
        .await
        .context("Failed to run migrations")?;

    Ok(pool)
}
"#
            }
            "SQLite" => {
                r#"use sqlx::sqlite::SqlitePool;
use anyhow::{Context, Result};

pub async fn create_pool(database_url: &str) -> Result<SqlitePool> {
    let pool = sqlx::sqlite::SqlitePool::connect(database_url)
        .await
        .context("Failed to connect to SQLite")?;

    // Run migrations
    sqlx::migrate!("./migrations")
        .run(&pool)
        .await
        .context("Failed to run migrations")?;

    Ok(pool)
}
"#
            }
            _ => return Ok(()),
        };

        std::fs::write(path.join("src/database.rs"), db_rs)
            .context("Failed to write database.rs")?;

        Ok(())
    }

    fn generate_migrations_dir(&self, path: &Path) -> Result<()> {
        std::fs::create_dir_all(path.join("migrations"))
            .context("Failed to create migrations directory")?;

        // Create initial migration
        let timestamp = chrono::Utc::now().format("%Y%m%d%H%M%S");
        let migration_dir = path.join(format!("migrations/{}_init", timestamp));
        std::fs::create_dir_all(&migration_dir)
            .context("Failed to create migration directory")?;

        let up_sql = match self.config.database.as_str() {
            "PostgreSQL" => "-- Add your initial migration here\n",
            "MySQL" => "-- Add your initial migration here\n",
            "SQLite" => "-- Add your initial migration here\n",
            _ => "",
        };

        std::fs::write(migration_dir.join("up.sql"), up_sql)
            .context("Failed to write up.sql")?;

        std::fs::write(migration_dir.join("down.sql"), "-- Reverse migration\n")
            .context("Failed to write down.sql")?;

        Ok(())
    }

    fn create_directories(&self, path: &Path) -> Result<()> {
        let dirs = vec![
            "src/routes",
            "src/handlers",
            "src/models",
            "src/services",
            "src/repositories",
            "src/middleware",
            "tests",
        ];

        for dir in dirs {
            std::fs::create_dir_all(path.join(dir))
                .context(format!("Failed to create directory {}", dir))?;
        }

        // Create mod.rs files
        let mod_files = vec![
            ("src/routes/mod.rs", "use crate::state::AppState;\nuse axum::Router;\n\npub fn router(state: AppState) -> Router {\n    Router::new().with_state(state)\n}\n"),
            ("src/handlers/mod.rs", "// Handler implementations\n"),
            ("src/models/mod.rs", "// Data models\n"),
            ("src/services/mod.rs", "// Business logic\n"),
            ("src/repositories/mod.rs", "// Data access layer\n"),
            ("src/middleware/mod.rs", "// Middleware implementations\n"),
        ];

        for (file, content) in mod_files {
            std::fs::write(path.join(file), content)
                .context(format!("Failed to write {}", file))?;
        }

        Ok(())
    }
}
